sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build docker-demo-app docker-demo-app-tests
script: docker-compose run --rm -e "CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN" docker-demo-app-tests
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
