version: '2'
services:
  dev:
    build: .
    image: keboola/sapi-merged-export
    mem_limit: 64m
    tty: true
    stdin_open: true
    command: sh -c 'composer install && php vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php . && php vendor/bin/phpunit'
    volumes:
      - ./:/code
  tests-ci:
    image: keboola/docker-demo-app
    command: sh -c 'composer install && php vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php . && php vendor/bin/phpunit'